### ISSUE TITLE
Errors on make

### ISSUE THREAD

**Issue by kiwironnie** [TalkWithTLS/TalkWithTLS#30]
Having successfully run get_submodules.sh make (on Ubuntu 20.04) is returning the following errors. The build stops after successfully building the sample binaries. ```

compile: version "go1.10.4" does not match go tool version "go1.13.8"
 unicode/utf8
compile: version "go1.10.4" does not match go tool version "go1.13.8"
 runtime/internal/sys
compile: version "go1.10.4" does not match go tool version "go1.13.8"
 unicode
compile: version "go1.10.4" does not match go tool version "go1.13.8"
```
Solution would be appreciated.

**Comment by akarmegam** [comment]
I am not facing this issue, when I build with latest golang `1.19`. I have updated the README about latest golang installation. Please follow the steps and try building with latest golang.
