### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by pawansingal** [TalkWithTLS/TalkWithTLS#31]
ubuntu@ubuntu-VirtualBox:~/ssl-psk/TalkWithTLS$ make

echo "obj/src/utils/dtls_proxy.o obj/src/common/test_common.o"

obj/src/utils/dtls_proxy.o obj/src/common/test_common.o

Building boringssl-master...

pkgconfig not found. Disabling unwind tests.

In file included from /home/ubuntu/ssl-psk/TalkWithTLS/dependency/boringssl-master/third_party/googletest/src/gtest-all.cc:42:

/home/ubuntu/ssl-psk/TalkWithTLS/dependency/boringssl-master/third_party/googletest/src/gtest-death-test.cc: In function ‘bool testing::internal::StackGrowsDown()’:

/home/ubuntu/ssl-psk/TalkWithTLS/dependency/boringssl-master/third_party/googletest/src/gtest-death-test.cc:1287:24: error: ‘dummy’ may be used uninitialized [-Werror=maybe-uninitialized]

 1287 |   StackLowerThanAddress(&dummy, &result);

      |   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~

/home/ubuntu/ssl-psk/TalkWithTLS/dependency/boringssl-master/third_party/googletest/src/gtest-death-test.cc:1276:13: note: by argument 1 of type ‘const void*’ to ‘void testing::internal::StackLowerThanAddress(const void*, bool*)’ declared here

 1276 | static void StackLowerThanAddress(const void* ptr, bool* result) {

      |             ^~~~~~~~~~~~~~~~~~~~~

/home/ubuntu/ssl-psk/TalkWithTLS/dependency/boringssl-master/third_party/googletest/src/gtest-death-test.cc:1285:7: note: ‘dummy’ declared here

 1285 |   int dummy;

      |       ^~~~~

cc1plus: all warnings being treated as errors

make[3]: *** [CMakeFiles/boringssl_gtest.dir/build.make:76: CMakeFiles/boringssl_gtest.dir/third_party/googletest/src/gtest-all.cc.o] Error 1

make[2]: *** [CMakeFiles/Makefile2:286: CMakeFiles/boringssl_gtest.dir/all] Error 2

make[1]: *** [Makefile:91: all] Error 2

make: *** [Makefile:443: boringssl-master/build_dbg/ssl/libssl.a] Error 2

**Comment by akarmegam** [comment]
I feel `libunwind-dev` is missing in your env. I updated the dependencies which are required to install in README. Please install and try build. I am able to build it on ubuntu 20.04.

**Comment by pawansingal** [comment]
I tried again after installing the libunwind-dev pkg, same result.

ubuntu@ubuntu-VirtualBox:~/ssl-psk/TalkWithTLS$ make

Building boringssl-master...

pkgconfig not found. Disabling unwind tests.

In file included from /home/ubuntu/ssl-psk/TalkWithTLS/dependency/boringssl-master/third_party/googletest/src/gtest-all.cc:42:

/home/ubuntu/ssl-psk/TalkWithTLS/dependency/boringssl-master/third_party/googletest/src/gtest-death-test.cc: In function ‘bool testing::internal::StackGrowsDown()’:

/home/ubuntu/ssl-psk/TalkWithTLS/dependency/boringssl-master/third_party/googletest/src/gtest-death-test.cc:1287:24: error: ‘dummy’ may be used uninitialized [-Werror=maybe-uninitialized]

 1287 |   StackLowerThanAddress(&dummy, &result);

      |   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~

/home/ubuntu/ssl-psk/TalkWithTLS/dependency/boringssl-master/third_party/googletest/src/gtest-death-test.cc:1276:13: note: by argument 1 of type ‘const void*’ to ‘void testing::internal::StackLowerThanAddress(const void*, bool*)’ declared here

 1276 | static void StackLowerThanAddress(const void* ptr, bool* result) {

      |             ^~~~~~~~~~~~~~~~~~~~~

/home/ubuntu/ssl-psk/TalkWithTLS/dependency/boringssl-master/third_party/googletest/src/gtest-death-test.cc:1285:7: note: ‘dummy’ declared here

 1285 |   int dummy;

      |       ^~~~~

cc1plus: all warnings being treated as errors

make[3]: *** [CMakeFiles/boringssl_gtest.dir/build.make:76: CMakeFiles/boringssl_gtest.dir/third_party/googletest/src/gtest-all.cc.o] Error 1

make[2]: *** [CMakeFiles/Makefile2:286: CMakeFiles/boringssl_gtest.dir/all] Error 2

make[1]: *** [Makefile:91: all] Error 2

make: *** [Makefile:441: boringssl-master/build_dbg/ssl/libssl.a] Error 2

ubuntu@ubuntu-VirtualBox:~/ssl-psk/TalkWithTLS$ 

ubuntu@ubuntu-VirtualBox:~/ssl-psk/TalkWithTLS$ 

ubuntu@ubuntu-VirtualBox:~/ssl-psk/TalkWithTLS$ 

ubuntu@ubuntu-VirtualBox:~/ssl-psk/TalkWithTLS$ git status

On branch master

Your branch is up to date with 'origin/master'.



Changes not staged for commit:

  (use "git add <file>..." to update what will be committed)

  (use "git restore <file>..." to discard changes in working directory)

  (commit or discard the untracked or modified content in submodules)

	modified:   dependency/boringssl-master (new commits, modified content, untracked content)

	modified:   dependency/openssl-1.1.1 (new commits)

	modified:   dependency/openssl-1.1.1-rel (new commits)

	modified:   dependency/openssl-master (new commits, modified content)

	modified:   dependency/openssl-master-rel (new commits, modified content)



Untracked files:

  (use "git add <file>..." to include in what will be committed)

	Makefile.orig

	dependency/openssl-1.1.1.keep/



no changes added to commit (use "git add" and/or "git commit -a")

ubuntu@ubuntu-VirtualBox:~/ssl-psk/TalkWithTLS$ sudo apt install libunwind-dev

Reading package lists... Done

Building dependency tree... Done

Reading state information... Done

libunwind-dev is already the newest version (1.3.2-2build2).

The following packages were automatically installed and are no longer required:

  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libgstreamer-plugins-bad1.0-0 libva-wayland2

Use 'sudo apt autoremove' to remove them.

0 upgraded, 0 newly installed, 0 to remove and 40 not upgraded.

**Comment by pawansingal** [comment]
ubuntu@ubuntu-VirtualBox:~/ssl-psk/TalkWithTLS$ uname -a

Linux ubuntu-VirtualBox 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
